
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-04-28 11:03:32
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DapperExtensions.Mapper;
namespace NBCZ.Model
{	
    
    public partial class Pub_Department:BaseEntity<Pub_Department>
    {
        public Pub_Department()
        {
          //varchar主键 报错At least one Key column must be defined.
          Map(x => x.DeptCode).Key(KeyType.Assigned);
          AutoMap();
        }
    
		
		/// <summary>
		/// 部门编号
		/// </summary>		
		public string DeptCode { get; set; }
		
		/// <summary>
		/// 部门名称
		/// </summary>		
		public string DeptName { get; set; }
		
		/// <summary>
		/// 备注
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 上级部门编号
		/// </summary>		
		public string ParentCode { get; set; }
		
		/// <summary>
		/// 部门级别
		/// </summary>		
		public int DeptLevel { get; set; }
		
		/// <summary>
		/// 最后编辑人
		/// </summary>		
		public string Lmid { get; set; }
		
		/// <summary>
		/// 最后编辑时间
		/// </summary>		
		public DateTime? Lmdt { get; set; }
		
		/// <summary>
		/// 停用状态 默认0 未停用 1 停用
		/// </summary>		
		public bool? StopFlag { get; set; }
		   
    }
}

