//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-07-05 10:16:48
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DapperExtensions.Mapper;
using Newtonsoft.Json;
namespace NBCZ.Model
{	
    [JsonObject(MemberSerialization.OptIn)]
    public partial class Pub_Function:BaseEntity<Pub_Function>
    {
        public Pub_Function()
        {
          //varchar主键 报错At least one Key column must be defined.
          Map(x => x.FunctionCode).Key(KeyType.Assigned);
          AutoMap();
        }
    		 /// <summary>
     	/// 权限编号
     	/// </summary>
        [JsonProperty]	
		public string FunctionCode { get; set; }

		 /// <summary>
     	/// 英文编号
     	/// </summary>
        [JsonProperty]	
		public string FunctionEnglish { get; set; }

		 /// <summary>
     	/// 中文名称
     	/// </summary>
        [JsonProperty]	
		public string FunctionChina { get; set; }

		 /// <summary>
     	/// 说明
     	/// </summary>
        [JsonProperty]	
		public string FunctionDescrip { get; set; }

		 /// <summary>
     	/// 父节点
     	/// </summary>
        [JsonProperty]	
		public string ParentCode { get; set; }

		 /// <summary>
     	/// 是否为菜单 1菜单 0权限
     	/// </summary>
        [JsonProperty]	
		public bool MenuFlag { get; set; }

		 /// <summary>
     	/// 是否停用
     	/// </summary>
        [JsonProperty]	
		public bool? StopFlag { get; set; }

		 /// <summary>
     	/// 链接URL
     	/// </summary>
        [JsonProperty]	
		public string URLString { get; set; }

		 /// <summary>
     	/// 创建或修改时间
     	/// </summary>
        [JsonProperty]	
		public DateTime? editdate { get; set; }

		 /// <summary>
     	/// 修改人 名字加工号 张三(000001)
     	/// </summary>
        [JsonProperty]	
		public string editor { get; set; }

		 /// <summary>
     	/// 排序字段
     	/// </summary>
        [JsonProperty]	
		public int? sortidx { get; set; }

		 /// <summary>
     	/// navTab 嵌套  _blank 新窗口 dialog 弹出窗
     	/// </summary>
        [JsonProperty]	
		public string target { get; set; }

		 /// <summary>
     	/// 菜单图标class
     	/// </summary>
        [JsonProperty]	
		public string MenuIcon { get; set; }

		   
    }
}

