//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-08-17 11:06:13
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DapperExtensions.Mapper;
using Dapper.Contrib.Extensions;
using Newtonsoft.Json;

namespace NBCZ.Model
{	
    [Table("V_PubUser_Dept")]
[JsonObject(MemberSerialization.OptIn)]

    public sealed partial class V_PubUser_Dept
    {
     		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public int Id { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string UserCode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string UserName { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string RealName { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string UserPwd { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public bool Sex { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string IdentityNo { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public DateTime? Birthday { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string DeptCode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public bool ManagerFlag { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string Tel { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string EMail { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string QQ { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string Remark { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public bool StopFlag { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string Crid { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public DateTime? Crdt { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string Lmid { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public DateTime? Lmdt { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public DateTime? LoginDate { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string ProvinceCode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string CityCode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string RegionCode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string UserAddress { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string Wxcode { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string HeadUrl { get; set; }

		 /// <summary>
     	/// 
     	/// </summary>
		 [JsonProperty]	
		public string DeptName { get; set; }

		   
    }
}

